# generated on Wed 27 Apr 2016 21:48:50 BST

run: eulerPaper.pdf
	@echo "\n**" Ready! "**"
	@echo "(You may need to re/run Latex to get cross-references etc right)"
	
test: euler randomised-euler winelist.tex
	cat winelist.tex
	
# next line generated by ./relit -f eulerPaper.tex > t
Makefile TeX-mode-demo.tex euler.c hello.c randomised-euler.c relit-def.tex sedcommands wine.c: eulerPaper.tex relit  
	./relit "date=`date`" command-line-tag="" eulerPaper.tex

euler: euler.c
	@echo " --" Check euler.c 
	cc euler.c -o euler
	./euler

randomised-euler: randomised-euler.c
	@echo " --" Check randomised-euler.c
	cc randomised-euler.c -o randomised-euler
	./randomised-euler

winelist.tex: wine
	./wine > winelist.tex 

wine: wine.c
	@echo " --" Check wine.c 
	cc wine.c -o wine
	
lastwine.tex: winelist.tex
	tail -n 1 winelist.tex > lastwine.tex
	
linesofcode.tex: euler.c uncom
	./uncom < euler.c | wc -l > t; echo Euler.c has `cat t` lines of code
	echo "\\\\newcount\\linesofcode \\linesofcode"=`cat t` > linesofcode.tex
	rm t
	
sedgewickeslinesofcode.tex: java/DirectedEulerianCycle.java uncom
	./uncom < java/DirectedEulerianCycle.java | wc -l > t;
	echo "\\\\newcount\\linesofcode \\linesofcode"=`cat t` > sedgewickeslinesofcode.tex
	rm t
	
e.txt: euler.c sedcommands euler.c-tagged.txt
	sed -f sedcommands euler.c-tagged.txt > e.txt
	
allLinesofcode.tex: uncom 
	cat java/*.java | ./uncom | wc -l > t;
	echo "\\\\newcount\\linesofcode \\linesofcode"=`cat t` > allLinesofcode.tex
	rm t
	
relit: relit.c
	cc relit.c -o relit
	
linesofrelit.tex: relit.c
	expr `cat relit.c|wc -l` / 10 "*" 10 > linesofrelit.tex
	
uncom: uncom.c
	cc uncom.c -o uncom
	
index eulerPaper.ind: eulerPaper.idx
	makeindex eulerPaper.idx
	
eulerPaper.pdf eulerPaper.aux eulerPaper.idx: eulerPaper.tex linesofcode.tex sedgewickeslinesofcode.tex lastwine.tex winelist.tex allLinesofcode.tex linesofrelit.tex e.txt
	@echo
	@echo TRY RUNNING pdflatex eulerPaper.tex
	
eulerPaper.bbl: eulerPaper.aux
	bibtex eulerPaper.aux
	
man: relit.1
	man ./relit.1
	
clean: # leaves all the sources and the pdf file
	-rm euler.c euler randomised-euler.c randomised-euler winelist.tex lastwine.tex linesofcode.tex sedgewickeslinesofcode.tex hello.c allLinesofcode.tex linesofrelit.tex e.txt uncom relit t *-tagged.txt wine.c wine allinesofcode.tex
	-rm eulerPaper.aux eulerPaper.bbl eulerPaper.blg eulerPaper.log eulerPaper.synctex.gz 
	-rm eulerPaper.idx eulerPaper.dvi eulerPaper.ilg sedcommands TeX-mode-demo.tex relit-def.tex
	# -rm eulerPaper.ind  
